on: ["push", "pull_request"]

name: Coverage

jobs:

  Coveralls:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Use Node.js 10.x'
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: 'npm install, make test-coverage'
      run: |
        npm install
        make test-coverage
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
