on: ["push", "pull_request"]

name: Coverage

jobs:

  Coveralls:
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: Indicate completion to coveralls.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip3 install --upgrade coveralls
        pip3 install .
        coverage run -m pytest
        coveralls
