name: Tests

on: [push, pull_request]

jobs:

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: 'Lint with flake8'
        run: |
          pip install flake8
          flake8 . --count --show-source --statistics

  Pytest:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu", "macos", "windows"]
        python-version: [3.6, 3.7, 3.8, 3.9]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: 'Deploying miniconda'
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: true
      - name: 'Building & Testing conda package'
        run: |
          conda install pytest
          python -m pytest

  Check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: 'Deploying miniconda'
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          environment-file: conda.recipe/conda_build_env.yaml
          activate-environment: build
      - name: 'Updating conda'
        run: conda update --all -y
      - name: 'Installing make'
        run: conda install -y make
      - name: 'Checkout CI/CD Toolkit'
        uses: actions/checkout@v2
        with:
          repository: breakthewall/cicd-toolkit
          path: cicd-toolkit
          persist-credentials: false
          fetch-depth: 0
      - name: 'Checking package'
        run: |
          cd cicd-toolkit
          make check-buildenv env=check
          conda run -n check make check
